//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TorteNS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class klijent
    {
        public int idKlijenta { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string telefon { get; set; }
        public string telefon2 { get; set; }
        public string email { get; set; }
        public string fblink { get; set; }
        public string napomene { get; set; }
        public string adresa { get; set; }
        public Nullable<float> rating { get; set; }
        public int status { get; set; }
    }
}
