//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TorteNS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class proizvod
    {
        public proizvod()
        {
            this.slikes = new HashSet<slike>();
        }
    
        public string naziv { get; set; }
        public string cena { get; set; }
        public string tezina { get; set; }
        public string opis { get; set; }
        public string kolicina { get; set; }
        public int idGrupe { get; set; }
        public int idProizvoda { get; set; }
        public Nullable<int> danispremanja { get; set; }
    
        public virtual ICollection<slike> slikes { get; set; }
    }
}
