//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TorteNS.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TorteDatabase : DbContext
    {
        public TorteDatabase()
            : base("name=TorteDatabase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<grupa> grupas { get; set; }
        public DbSet<klijent> klijents { get; set; }
        public DbSet<porudzbine> porudzbines { get; set; }
        public DbSet<proizvod> proizvods { get; set; }
        public DbSet<slike> slikes { get; set; }
        public DbSet<slikeporudzbine> slikeporudzbines { get; set; }
    }
}
